version: "3.7"

services:
  mongo:
    image: mongo
    container_name: db_hackaton_ccr
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: "root_user"
      MONGODB_DATABASE: "hackatonccrr"
      MONGODB_PASS: "hackatonccrr_private"
    volumes:
      - /usr/local/share/save-point-docker/mongo/:/data/db
    networks:
      hackaton_ccr:
        ipv4_address: 172.18.10.1

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:12
    container_name: api_hackaton_ccr
    env_file:
      - .env
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - mongo
    networks:
      hackaton_ccr:
        ipv4_address: 172.18.10.2

networks:
  hackaton_ccr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.10.0/16
